config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  resources :projects do
    resources :etherpads
    resources :project_users
    resources :milestones do
      resources :tasks do
        resources :comments
        member do
          get 'start_status'
          get 'review_status'
          get 'complete_status'
        end
      end
    end
  end

  devise_for :user, :path => '', :path_names => { :users => "/" }

end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  belongs_to :project
  has_many :tasks, dependent: :destroy

  @valid = ['Created', 'Started', 'Pending Review', 'Completed']
  
  validates_presence_of :due_date, :project_id
  validates :status, presence: true, :inclusion=> { :in => @valid }
  validates :name, presence: true, uniqueness: { case_sensitive: false } 
  validate :due_date_cannot_be_in_the_past

  def due_date_cannot_be_in_the_past
    errors.add(:due_date, "can't be in the past") if
      !due_date.blank? and due_date < Date.today
  end

end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  before_filter :user_not_signed_in
  before_action :set_project
  before_filter :user_is_project_user_or_owner
  before_action :set_milestone, only: [:show, :edit, :update, :destroy]

  # GET /milestones
  # GET /milestones.json
  def index
    @milestones = Milestone.where(project_id: @project.id)
  end

  # GET /milestones/1
  # GET /milestones/1.json
  def show
    update_milestone_status
    @tasks = Task.where(milestone_id: @milestone.id).order(:priority)
    @comments = Array.new
    @tasks.each {|t| Comment.where(task_id: t.id).each {|c| @comments << c} }
    @comments.sort! { |a, b| b.created_at <=> a.created_at  }
  end

  # GET /milestones/new
  def new
    @milestone = Milestone.new
  end

  # GET /milestones/1/edit
  def edit
  end

  # POST /milestones
  # POST /milestones.json
  def create
    @milestone = @project.milestones.new(milestone_params)
    @milestone.project_id = @project.id
    @milestone.status = "Created"

    respond_to do |format|
      if @milestone.save
        format.html { redirect_to project_milestones_path(@project), notice: 'Milestone was successfully created.' }
        format.json { render :show, status: :created, location: @milestone }
      else
        format.html { render :new }
        format.json { render json: @milestone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /milestones/1
  # PATCH/PUT /milestones/1.json
  def update
    respond_to do |format|
      if @milestone.update(milestone_params)
        format.html { redirect_to project_milestones_path(@project), notice: 'Milestone was successfully changed.' }
        format.json { render :show, status: :ok, location: @milestone }
      else
        format.html { render :edit }
        format.json { render json: @milestone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /milestones/1
  # DELETE /milestones/1.json
  def destroy
    @milestone.destroy
    respond_to do |format|
      format.html { redirect_to project_milestones_path(@project), notice: 'Milestone was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_milestone
      @milestone = Milestone.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def milestone_params
      params.require(:milestone).permit(:due_date, :name)
    end
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/views/milestones/_form.html.erb
<%= form_for [@project, @milestone] do |f| %>
  <% if @milestone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@milestone.errors.count, "error") %> prohibited this milestone from being saved:</h2>

      <ul>
      <% @milestone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :due_date %>
    <%= f.date_select :due_date %>
  </div>
  <div class="actions">
    <%= f.submit nil, :class => "btn btn-custom" %>
    <%= link_to 'Back', project_milestones_path(@project), class: 'btn' %>
  </div>
<% end %>

app/views/milestones/edit.html.erb
<div class="row">
    <div class="col-xs-4">
    <div class="align">
	 <p><strong>Project Leader:</strong></p>
	 <p><%= @project.user.email %></p>
	 <br>
	 <p><strong>Description:</strong></p>
	 <p><%= @project.description %></p>

	 <% if current_user == @project.user %>
	    <%= link_to 'Edit', edit_project_path(@project), :class => 'btn btn-custom' %> 
	 <% end %>
    </div>
    </div>
	<div class="col-xs-8 offset4">
		<div class='files'>
		 	<h3>Editing Milestone</h3>
		 	<%= render 'form' %>
		</div>
	</div>
</div>

app/views/milestones/index.html.erb
<div class="row">
  <div class="col-xs-4">
    <div class="align">
   <p><strong>Project Leader:</strong></p>
   <p><%= @project.user.email %></p>
   <br>
   <p><strong>Description:</strong></p>
   <p><%= @project.description %></p>

   <% if current_user == @project.user %>
      <%= link_to 'Edit', edit_project_path(@project), :class => 'btn btn-custom' %> 
   <% end %>
    </div>
    </div>

  <div class="col-xs-8 offset4">
    <div class='milestones'>
    <div class="row">
    <br>
    <p><h3>Listing Milestones</h3></p>
    <% if @milestones.count == 0 %>
      Your project requires some planning! 
      <br><br>
    <% else %>
      <table class="table table-hover table-striped table-bordered">
        <thead>
          <tr>
            <th>Name</th>
            <th>Due date</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @milestones.each do |milestone| %>
            <tr>
              <td class="vert-align"><%= link_to milestone.name, project_milestone_path(@project, milestone), class: 'btn btn-link' %></td>
              <td class="vert-align"><%= milestone.due_date %></td>
              <% if milestone.status == 'Completed' %>
                <td class="vert-align"><%= milestone.status %></td>
              <% end %>
              <td class="vert-align"><%= link_to 'Remove', project_milestone_path(@project, milestone), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
    <%= link_to 'New Milestone', new_project_milestone_path(@project), :class => 'btn btn-custom' %>
    </div>
  </div>  
</div>
</div>

app/views/milestones/new.html.erb
<div class="row">
    <div class="col-xs-4">
    <div class="align">
	 <p><strong>Project Leader:</strong></p>
	 <p><%= @project.user.email %></p>
	 <br>
	 <p><strong>Description:</strong></p>
	 <p><%= @project.description %></p>

	 <% if current_user == @project.user %>
	    <%= link_to 'Edit', edit_project_path(@project), :class => 'btn' %> 
	 <% end %>
    </div>
    </div>
	<div class="col-xs-8 offset4">
		<div class='files'>
		 	<h3>New Milestone</h3>
		 	<%= render 'form' %>
		</div>
	</div>
</div>

app/views/milestones/show.html.erb
<div class="row">
  <div class="col-xs-4">
    <div class="align">
   <p><strong>Project Leader:</strong></p>
   <p><%= @project.user.email %></p>
   <br>
   <p><strong>Description:</strong></p>
   <p><%= @project.description %></p>

   <% if current_user == @project.user %>
      <%= link_to 'Edit', edit_project_path(@project), :class => 'btn btn-custom' %> 
   <% end %>
    </div>
    </div>

  <div class="col-xs-8 offset4">
   <div class='milestones'>
    <div class="row">
    <br>
    <p>
      <h3>Milestone: <%= @milestone.name %></h3>
    </p>

    <p>
      <strong>Due date:</strong>
      <%= @milestone.due_date %>
    </p>

    <% if !@milestone.completion_date.nil? %>
      <p>
        <strong>Completion date:</strong>
        <%= @milestone.completion_date %>
      </p>
    <% end %>

    <p>
      <strong>Status:</strong>
      <%= @milestone.status %>
    </p>

    <%= link_to 'Edit', edit_project_milestone_path(@project, @milestone), :class => 'btn btn-custom' %> 
    <%= link_to 'Back', project_milestones_path(@project), :class => 'btn' %>

    <br><br><br>
    <%= render template: 'tasks/index' %>
    <br><br><br>

    <% if @comments.count != 0 %>  
      <%= render template: 'comments/index' %>
    <% end %>
    </div>
    </div>
  </div>
</div>