config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  resources :projects do
    resources :etherpads
    resources :project_users
    resources :milestones do
      resources :tasks do
        resources :comments
        member do
          get 'start_status'
          get 'review_status'
          get 'complete_status'
        end
      end
    end
  end

  devise_for :user, :path => '', :path_names => { :users => "/" }

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  has_many :comments, dependent: :destroy

  @valid = ['Created', 'Started', 'Pending Review', 'Completed']

  validates_presence_of :name, :description, :priority, :user_email, :milestone_id, :status
  validates :difficulty, presence: true, :inclusion=> { :in => 1..10 }
  validates :status, :inclusion=> { :in => @valid }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :user_not_signed_in
  before_action :set_project
  before_filter :user_is_project_user_or_owner
  before_action :set_milestone
  before_action :set_task, except: [:create, :new, :index]

  # GET /tasks
  # GET /tasks.json
  def index
    redirect_to project_milestone_path(@project, @milestone)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @comments = Comment.where(task: @task)
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = @milestone.tasks.new(task_params)
    @task.milestone_id = @milestone.id
    @task.status = "Created"
    @task.user_email = current_user.email

    if !Task.find_by(name: @task.name, milestone_id: @task.milestone_id).nil?
      redirect_to new_project_milestone_task_path(@project, @milestone), notice: 'Task already exists'
    else
      respond_to do |format|
        if @task.save
          format.html { redirect_to project_milestone_path(@project, @milestone), notice: 'Task was successfully created.' }
          format.json { render :show, status: :created, location: @task }
        else
          format.html { render :new }
          format.json { render json: @task.errors, status: :unprocessable_entity }
        end
        Comment.create(comment: "#{@task.name} was created", task_id: @task.id, creator_email: current_user.email)
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_milestone_task_path(@project, @milestone, @task), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to project_milestone_path(@project, @milestone), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def start_status
    @task.status = 'Started'
    @task.owner_email = current_user.email
    @task.save
    Comment.create(comment: "#{@task.name} has been started by #{@current_user.email}", task_id: @task.id, creator_email: current_user.email)
    redirect_to project_milestone_path(@project, @milestone)
  end

  def review_status
    @task.status = 'Pending Review'
    @task.save
    Comment.create(comment: "#{@task.name} has been finished by #{@current_user.email} and is awaiting review by #{@task.user_email}", task_id: @task.id, creator_email: current_user.email)
    redirect_to project_milestone_path(@project, @milestone)
  end

  def complete_status
    @task.status = 'Completed'
    @task.save
    Comment.create(comment: "#{@task.name} is completed", task_id: @task.id, creator_email: current_user.email)
    redirect_to project_milestone_path(@project, @milestone)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :description, :difficulty, :priority)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for [@project, @milestone, @task] do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :difficulty %><br>
    <%= f.select :difficulty, [['One day or less',1],['2 days',2],['3 days',3],['4 days',4],['5 days',5],['6 days',6],['7 days',7],['8 days',8],['9 days',9],['10 days or more',10]] %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
    <%= f.select :priority, [['Critical',1],['High',2],['Medium',3],['Low',4]] %>
  </div>
  <div class="field">
    <%= f.submit nil, :class => "btn btn-custom" %>
    <%= link_to 'Back', project_milestone_path(@project, @milestone), class: 'btn' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="row">
    <div class="col-xs-4">
    <div class="align">
   <p><strong>Project Leader:</strong></p>
   <p><%= @project.user.email %></p>
   <br>
   <p><strong>Description:</strong></p>
   <p><%= @project.description %></p>

   <% if current_user == @project.user %>
      <%= link_to 'Edit', edit_project_path(@project), :class => 'btn btn-custom' %> 
   <% end %>
    </div>
    </div>
  <div class="col-xs-8 offset4">
    <div class='files'>
      <h3>Editing Task</h3>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<h4>Tasks</h4>

<% if @tasks.count == 0 %>
Your milestone requires some planning! <br>
<% else %>
  <table class="table table-hover table-striped table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Creator</th>
        <th>Difficulty</th>
        <th>Priority</th>
        <th>Status</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td class="vert-align"><%= link_to task.name, project_milestone_task_path(@project, @milestone, task), class: 'btn btn-link' %></td>
          <td class="vert-align"><%= task.user_email %></td>
          <td class="vert-align"><%= task.difficulty %></td>
          <td class="vert-align"><%= task.priority %></td>
          <td class="vert-align"><%= task.status %></td>
          <% if task.status == 'Created' %>
            <td class="vert-align"><%= link_to 'Start', start_status_project_milestone_task_path(@project, @milestone, task), class: 'btn btn-custom' %></td>
          <% elsif task.status == 'Started' && current_user.email == task.owner_email%>
            <td class="vert-align"><%= link_to 'Finish', review_status_project_milestone_task_path(@project, @milestone, task), class: 'btn btn-custom' %></td>
          <% elsif task.status == 'Pending Review' && current_user.email == task.user_email%>
            <td class="vert-align"><%= link_to 'Reviewed', complete_status_project_milestone_task_path(@project, @milestone, task), class: 'btn btn-custom' %></td>
          <% end %>
          <td class="vert-align"><%= link_to 'Destroy', project_milestone_task_path(@project, @milestone, task), method: :delete, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to 'New Task', new_project_milestone_task_path(@project, @milestone), :class => "btn btn-custom" %>

app/views/tasks/new.html.erb
<div class="row">
    <div class="col-xs-4">
    <div class="align">
	 <p><strong>Project Leader:</strong></p>
	 <p><%= @project.user.email %></p>
	 <br>
	 <p><strong>Description:</strong></p>
	 <p><%= @project.description %></p>

	 <% if current_user == @project.user %>
	    <%= link_to 'Edit', edit_project_path(@project), :class => 'btn btn-custom' %> 
	 <% end %>
    </div>
    </div>
	<div class="col-xs-8 offset4">
		<div class='files'>
		 	<h3>New Task</h3>
		 	<%= render 'form' %>
		</div>
	</div>
</div>

app/views/tasks/show.html.erb
<div class="row">
  <div class="col-xs-4">
    <div class="align">
   <p><strong>Project Leader:</strong></p>
   <p><%= @project.user.email %></p>
   <br>
   <p><strong>Description:</strong></p>
   <p><%= @project.description %></p>

   <% if current_user == @project.user %>
      <%= link_to 'Edit', edit_project_path(@project), :class => 'btn' %> 
   <% end %>
    </div>
    </div>
  <div class="col-xs-8 offset4">
   <div class='milestones'>
    <div class="row">
    <br>
    <p>
      <h3>Task: <%= @task.name %></h3>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @task.description %>
    </p>

    <% if !@task.owner_email.nil? %>
      <p>
        <strong>Owner:</strong>
        <%= @task.owner_email %>
      </p>
    <% end %>

    <p>
      <strong>Status:</strong>
      <%= @task.status %>
    </p>

    <p>
      <strong>Priority:</strong>
      <%= @task.priority %>
      <strong>Difficulty:</strong>
      <%= @task.difficulty %>
    </p>
    <%= link_to 'Edit', edit_project_milestone_task_path(@project, @milestone, @task), class: 'btn btn-custom' %>
    <%= link_to 'Back', project_milestone_tasks_path(@project, @milestone), class: 'btn' %>

    <br><br><br>
    <%= render template: 'comments/index' %>
    <%= link_to 'Add Comment', new_project_milestone_task_comment_path(@project, @milestone, @task), class: 'btn btn-custom' %>
      </div>
    </div>
  </div>
</div>