config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  resources :projects do
    resources :etherpads
    resources :project_users
    resources :milestones do
      resources :tasks do
        resources :comments
        member do
          get 'start_status'
          get 'review_status'
          get 'complete_status'
        end
      end
    end
  end

  devise_for :user, :path => '', :path_names => { :users => "/" }

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates_presence_of :name, :description

  belongs_to :user
  has_many :project_users, dependent: :destroy
  has_many :milestones, dependent: :destroy
  has_many :etherpads, dependent: :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  require 'burndown_chart.rb'

  before_filter :user_not_signed_in
  before_filter :user_is_project_owner, only: [:edit, :update, :destroy]
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :set_project_user, only: :show
  before_filter :user_is_project_user_or_owner, only: :show

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.where(user: current_user)
    ProjectUser.where(user_id: current_user).each do |pjuser|
      Project.where(id: pjuser.project_id).each { |pj| @projects << pj }
    end 

  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    if @project.milestones.count != 0 && !@project.started_at.nil?
      @chart = Burndown_chart.create_burndown_chart(@project)
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project_user from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.submit nil, :class => "btn btn-custom" %>
    <% if request.original_url =~ /\/projects\/new/ %>
      <%= link_to 'Cancel', projects_path, :class => 'btn' %>
    <% else %>
      <%= link_to 'Cancel', project_path(@project), :class => 'btn' %>
    <% end %>
  </div>

<% end %>

app/views/projects/edit.html.erb
<div class="row">
    <div class="col-xs-4">
    <div class="align">
	 <p><strong>Project Leader:</strong></p>
	 <p><%= @project.user.email %></p>
	 <br>
	 <p><strong>Description:</strong></p>
	 <p><%= @project.description %></p>

	 <% if current_user == @project.user %>
	    <%= link_to 'Edit', edit_project_path(@project), :class => 'btn btn-custom' %> 
	 <% end %>
    </div>
    </div>
	<div class="col-xs-8 offset4">
		<div class='files'>
		 	<h3>Editing Project</h3>
		 	<%= render 'form' %>
		</div>
	</div>
</div>

app/views/projects/index.html.erb
<br>
<h1>Listing projects</h1>
<br><br>
<div class="table-responsive">
  <table class="table table-hover table-striped table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td class="vert-align"> <%= link_to project.name, project, class: "btn btn-link" %></td>
          <td class="vert-align"> <%= project.description %></td>
          <td class="vert-align">
            <% if current_user == project.user %>
                <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>
<%= link_to 'New Project', new_project_path, class: 'btn btn-custom' %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
  <div class="row">
    <div class="col-xs-4">
    <div class="align">
	 <p><strong>Project Leader:</strong></p>
	 <p><%= @project.user.email %></p>
	 <br>
	 <p><strong>Description:</strong></p>
	 <p><%= @project.description %></p>

	 <% if current_user == @project.user %>
	    <%= link_to 'Edit', edit_project_path(@project), :class => 'btn btn-custom' %> 
	 <% end %>
    </div>
    </div>
    <div class="col-xs-8 offset4">
      <div class="row">
      <br><br>
	    <% if @project.milestones.count != 0 && !@project.started_at.nil? %>
		 <div class="chart" id='chart'></div>
		  <%= render_chart @chart, 'chart' %>
	  <% end %>
	   <div class="col-xs-8">
	     <%= render template: 'project_users/index' %>
	  </div> 
	</div>
  </div>