config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'

  resources :projects do
    resources :etherpads
    resources :project_users
    resources :milestones do
      resources :tasks do
        resources :comments
        member do
          get 'start_status'
          get 'review_status'
          get 'complete_status'
        end
      end
    end
  end

  devise_for :user, :path => '', :path_names => { :users => "/" }

end

app/models/etherpad.rb
class Etherpad < ActiveRecord::Base
  belongs_to :project

  validates_presence_of :creator, :project_id
  validates :file, presence: true, uniqueness: { case_sensitive: true } 
  validates :name, presence: true, uniqueness: { case_sensitive: false } 
end

app/controllers/etherpads_controller.rb
class EtherpadsController < ApplicationController
  require 'securerandom'
  before_filter :user_not_signed_in
  before_action :set_project
  before_filter :user_is_project_user_or_owner
  before_action :set_etherpad, only: [:show, :edit, :update, :destroy]

  # GET /etherpads
  # GET /etherpads.json
  def index
    @etherpads = Etherpad.where(project_id: @project.id)
  end

  # GET /etherpads/1
  # GET /etherpads/1.json
  def show
  end

  # GET /etherpads/new
  def new
    @etherpad = Etherpad.new
  end

  # GET /etherpads/1/edit
  def edit
  end

  # POST /etherpads
  # POST /etherpads.json
  def create
    @etherpad = @project.etherpads.new(etherpad_params)
    @etherpad.creator = current_user.email
    @etherpad.file = "https://beta.etherpad.org/" + SecureRandom.hex

    respond_to do |format|
      if @etherpad.save
        format.html { redirect_to project_etherpads_path(@project), notice: 'Etherpad was successfully created.' }
        format.json { render :show, status: :created, location: @etherpad }
      else
        format.html { render :new }
        format.json { render json: @etherpad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /etherpads/1
  # PATCH/PUT /etherpads/1.json
  def update
    respond_to do |format|
      if @etherpad.update(etherpad_params)
        format.html { redirect_to project_etherpads_path(@project), notice: 'Etherpad was successfully updated.' }
        format.json { render :show, status: :ok, location: @etherpad }
      else
        format.html { render :edit }
        format.json { render json: @etherpad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /etherpads/1
  # DELETE /etherpads/1.json
  def destroy
    @etherpad.destroy
    respond_to do |format|
      format.html { redirect_to project_etherpads_path(@project), notice: 'Etherpad was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_etherpad
      @etherpad = Etherpad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def etherpad_params
      params.require(:etherpad).permit(:name, :file, :creator)
    end
end

app/helpers/etherpads_helper.rb
module EtherpadsHelper
end

app/views/etherpads/_form.html.erb
<%= form_for [@project, @etherpad] do |f| %>
  <% if @etherpad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@etherpad.errors.count, "error") %> prohibited this file from being saved:</h2>

      <ul>
      <% @etherpad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit nil, class: "btn btn-custom" %>
    <%= link_to 'Back', project_etherpads_path(@project), class: 'btn' %>
  </div>
<% end %>

app/views/etherpads/edit.html.erb
<div class="row">
    <div class="col-xs-4">
	    <div class="align">
			 <p><strong>Project Leader:</strong></p>
			 <p><%= @project.user.email %></p>
			 <br>
			 <p><strong>Description:</strong></p>
			 <p><%= @project.description %></p>

			 <% if current_user == @project.user %>
			    <%= link_to 'Edit', edit_project_path(@project), :class => 'btn' %> 
			 <% end %>
			</div>
    </div>
	<div class="col-xs-8 offset4">
		<div class='files'>
		 	<h3>Change File Name</h3>
		 	<%= render 'form' %>
		</div>
	</div>
</div>

app/views/etherpads/index.html.erb
<div class="row">
  <div class="col-xs-4">
    <div class="align">
   <p><strong>Project Leader:</strong></p>
   <p><%= @project.user.email %></p>
   <br>
   <p><strong>Description:</strong></p>
   <p><%= @project.description %></p>

   <% if current_user == @project.user %>
      <%= link_to 'Edit', edit_project_path(@project), :class => 'btn btn-custom' %> 
   <% end %>
    </div>
    </div>
<div class="col-xs-8 offset4">
<br>
  <div class="files">
  <p><h3>Listing Files</h3></p><br>
  <% if @etherpads.count == 0 %>
    Your project has no files. Get started! <br><br>
  <% else %>
    <table class="table table-hover table-striped table-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th>Creator</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @etherpads.each do |etherpad| %>
          <tr>
            <td class="vert-align"><%= link_to etherpad.name, project_etherpad_path(@project, etherpad), class: "btn btn-link" %></td>
            <td class="vert-align"><%= etherpad.creator %></td>
            <td class="vert-align">
            <%= link_to 'Edit', edit_project_etherpad_path(@project, etherpad), class: 'btn btn-custom' %>
            <%= link_to 'Destroy', project_etherpad_path(@project, etherpad), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
  <%= link_to 'New File', new_project_etherpad_path(@project), class: "btn btn-custom" %>
</div>
</div>
</div>

app/views/etherpads/new.html.erb
<div class="row">
    <div class="col-xs-4">
    <div class="align">
	 <p><strong>Project Leader:</strong></p>
	 <p><%= @project.user.email %></p>
	 <br>
	 <p><strong>Description:</strong></p>
	 <p><%= @project.description %></p>

	 <% if current_user == @project.user %>
	    <%= link_to 'Edit', edit_project_path(@project), :class => 'btn btn-custom' %> 
	 <% end %>
    </div>
    </div>
	<div class="col-xs-8 offset4">
		<div class='files'>
		 	<h3>New File</h3>
		 	<%= render 'form' %>
		</div>
	</div>
</div>

app/views/etherpads/show.html.erb
  <div class="row">
    <div class="col-xs-4">
    <div class="align">
	 <p><strong>Project Leader:</strong></p>
	 <p><%= @project.user.email %></p>
	 <br>
	 <p><strong>Description:</strong></p>
	 <p><%= @project.description %></p>

	 <% if current_user == @project.user %>
	    <%= link_to 'Edit', edit_project_path(@project), :class => 'btn btn-custom' %> 
	 <% end %>
    </div>
    </div>
    <div class="col-xs-8 offset4">
      <div class="etherpad">
      <br>
        <iframe src= <%= @etherpad.file %> width=770 height=700></iframe>
        <br>
        <%= link_to 'Back', project_etherpads_path(@project), class: 'btn' %>
        <br><br>
      </div>
	</div>
  </div>